server:
  port: 6001

spring:
  application:
    name: fairticket
  datasource:
    url: jdbc:postgresql://localhost:5432/fairticket
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

jwt:
  signing:
    secret: ${JWT_SIGNING_SECRET:change-this-secret-key-with-at-least-32-characters}
    ttl: ${JWT_SIGNING_TTL:3600000}
